### ISSUE TITLE
Clarify rules

### ISSUE THREAD

**Issue by Radiumio** [ArmaAchilles/ZGM_Achilles_Collection#25]
According to some members the rules are not clear enough.

Representing controversial subjects is obviously not allowed and falls under respect.
However, an individual rule for this may be better, or additional clarification.

Remote-controlling AI to unfairly punish players or hinder them unjustifiably in a mission should also be an enforced rule *(or expanded upon under Zeus abuse)*.

**Comment by CreepPork** [comment]
Fixed in #26.
